const imageData = [
    { id: 'ii_1_obelisk', src: 'media/ii_1_obelisk.jpg', description: 'The Unfinished Obelisk in Aswan, Egypt' },
    { id: 'ii_2_pounding', src: 'media/ii_2_pounding.jpg', description: 'Pounding Stones found at the site in Aswan' },
    { id: 'ii_3_granite', src: 'media/ii_3_granite.jpg', description: 'Red granite chemically etched with molten natron' },
    { id: 'ii_6_pamukkale', src: 'media/ii_6_pamukkale.jpg', description: 'Natural limestone precipitation in Pamukkale, Turkey' },
    { id: 'ii_7_salinity', src: 'media/ii_7_salinity.jpg', description: 'Soil salinization at work' },
    { id: 'ii_8_koh', src: 'media/ii_8_koh.jpg', description: 'Etching granite with potassium hydroxide, 406 degrees Celsius' },
    { id: 'ii_9_chemical', src: 'media/ii_9_chemical.jpg', description: 'Beautiful chemical garden made from waterglass' },
    { id: 'ii_10_coin', src: 'media/ii_10_coin.jpg', description: 'The first ever Coin Excalibur in the 21st century' },
    { id: 'iv_1_menhir', src: 'media/iv_1_menhir.jpg', description: 'Menhir da Meada, Spain' },
    { id: 'iv_2_limestone', src: 'media/iv_2_limestone.mp4', description: 'Natural limestone found below a fire pit' },
    { id: 'iv_3_dolmen', src: 'media/iv_3_dolmen.jpg', description: 'Dolmen en el parque de Bens, La Coruña, Spain' },
    { id: 'iv_4_castle', src: 'media/iv_4_castle.jpg', description: 'Castle of Neuschwanstein, Germany' },
    { id: 'iv_5_machu', src: 'media/iv_5_machu.jpg', description: 'Imprints of wooden boards on a wall in Machu Picchu, Peru' },
    { id: 'v_1_pouring', src: 'media/v_1_pouring.mp4', description: 'Pouring molten natron onto a granite slab' },
    { id: 'v_2_scoop', src: 'media/v_2_scoops.jpg', description: 'Scoop marks on and around the Unfinished Obelisk' },
    { id: 'v_4_impala', src: 'media/v_4_impala.jpg', description: 'Impala black granite chemically etched with molten natron' },
    { id: 'v_5_blue', src: 'media/v_5_blue.jpg', description: 'Is this the famous Egyptian Blue?' },
    { id: 'v_6_rekhmire', src: 'media/v_6_rekhmire.jpg', description: 'Tomb of Rekhmire mural' },
    { id: 'v_10_molten', src: 'media/v_10_molten.mp4', description: 'Molten natron boiling in a tin can' },
    { id: 'v_12_sigiriya', src: 'media/v_12_sigiriya.jpg', description: 'Sigiriya, a huge granite rock "carved"' },
    { id: 'v_14_quenco', src: 'media/v_14_quenco.jpg', description: 'Quenco, a bit unusual "ceremonial place"' },
    { id: 'v_15_bomarzo', src: 'media/v_15_bomarzo.jpg', description: 'Bomarzo, Italy, stairs to heaven/nowhere' },
    { id: 'v_17_stone59', src: 'media/v_17_stone59.jpg', description: 'Scoopmarks on Stone 59, Stonehenge' },
    { id: 'v_18_stone60', src: 'media/v_18_stone60.jpg', description: 'Stone 60 The Outlier, Stonehenge' },
    { id: 'v_20_coating', src: 'media/v_20_coating.mp4', description: 'Not polishing, coating. Coating with waterglass.' },
    { id: 'vi_6_sacsa', src: 'media/vi_6_sacsa.jpg', description: 'Strange stone "carving" error in Sacsayhuaman, Peru' },
    { id: 'vi_7_hidro', src: 'media/vi_7_hidro.mp4', description: 'Silica hydrogel made from waterglass and baking soda' },
    { id: 'vi_8_bench', src: 'media/vi_8_bench.jpg', description: '...' },
    { id: 'vi_10_sillustani', src: 'media/vi_10_sillustani.jpg', description: 'Absolutely horrible stone masonry at Sillustani, Peru' },
    { id: 'vi_11_holes', src: 'media/vi_11_holes.jpg', description: 'Precision holes "carved" in between the cast stones' },
    { id: 'vi_12_cutimbo', src: 'media/vi_12_cutimbo.jpg', description: '"Carved" figurines on a stone. Cutimbo, Peru.' },
    { id: 'vi_14_utah', src: 'media/vi_14_utah.jpg', description: 'Hand prints in a rock wall, Utah, USA' },
    { id: 'vi_16_rosetta', src: 'media/vi_16_rosetta.jpg', description: 'Rosette Stone front and back' },
    { id: 'aaa', src: 'bbb', description: 'ccc' }
    // Vesszőőőő!
];